# Generated by Django 5.1.15 on 2026-06-11 23:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aoi', django.contrib.gis.db.models.fields.PolygonField(help_text='Polígono GeoJSON dibujado por el usuario', srid=4326)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('n_clusters', models.PositiveSmallIntegerField(default=4)),
                ('algorithm', models.CharField(choices=[('kmeans', 'K-Means'), ('dbscan', 'DBSCAN')], default='kmeans', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusters_geojson', models.JSONField(help_text='FeatureCollection con las zonas clusterizadas')),
                ('clusters_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('statistics', models.JSONField(help_text='Estadísticas resumidas por cluster e índice')),
                ('report_markdown', models.TextField(blank=True, default='')),
                ('satellite_collection', models.CharField(default='COPERNICUS/S2_SR_HARMONIZED', max_length=64)),
                ('images_used', models.PositiveIntegerField(default=0)),
                ('cloud_cover_max', models.FloatField(default=20.0)),
                ('processing_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['user', 'status'], name='analysis_an_user_id_a59fd4_idx'),
        ),
    ]
