# Generated by Django 5.1.15 on 2026-06-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='heatmap_layers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
