# Generated by Django 5.1.15 on 2026-06-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_heatmap_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
