# Generated by Django 5.1.15 on 2026-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='indices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='study_type',
            field=models.CharField(default='agro', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='use_pca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('dbscan', 'DBSCAN'), ('hdbscan', 'HDBSCAN')], default='kmeans', max_length=16),
        ),
    ]
