# Generated by Django 5.1.15 on 2026-06-22 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisrequest_indices_analysisrequest_study_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyses_allowed', models.PositiveIntegerField(default=1, help_text='Número de análisis permitidos')),
                ('analyses_used', models.PositiveIntegerField(default=0, help_text='Número de análisis realizados')),
                ('max_area_ha', models.FloatField(default=1.0, help_text='Área máxima permitida por análisis en hectáreas')),
                ('max_date_range_days', models.PositiveIntegerField(default=31, help_text='Rango máximo de fechas en días')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
